
[Wallbash]
text               = FFD8CC
subtext            = F0BBAA
nav-active-text    = E6AC9A
main               = 1A1219
sidebar            = 1A1219
player             = 1A1219
card               = 1A1219
shadow             = 52294D
main-secondary     = 6B3A4F
button             = F0B2AA
button-secondary   = E6A39A
button-active      = C2827A
button-disabled    = 4D333E
nav-active         = 6B403A
play-button        = 7D514B
tab-active         = 4D333E
notification       = 1A1219
notification-error = 1A1219
playback-bar       = 1A1219
misc               = 4D333E

; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous
